// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import AccountLayout from '~app/account.../layout'
import Account from '~app/account.../page'

import NotFound from '~components/common/NotFound'

function AccountSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<AccountLayout><Outlet /></AccountLayout>}
      >
        <Route
          index
          element={<Account />}
        />
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default AccountSubRouter
