// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import AdministratorLayout from '~app/administrator.../layout'
import Administrator from '~app/administrator.../page'
import EmailsLayout from '~app/administrator.../emails/layout'
import Emails from '~app/administrator.../emails/page'
import UsersLayout from '~app/administrator.../users/layout'
import Users from '~app/administrator.../users/page'
import GuildsLayout from '~app/administrator.../guilds/layout'
import Guilds from '~app/administrator.../guilds/page'

import NotFound from '~components/common/NotFound'

function AdministratorSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<AdministratorLayout><Outlet /></AdministratorLayout>}
      >
        <Route
          index
          element={<Administrator />}
        />
        <Route
          path="emails"
          element={<EmailsLayout><Outlet /></EmailsLayout>}
        >
          <Route
            index
            element={<Emails />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="users"
          element={<UsersLayout><Outlet /></UsersLayout>}
        >
          <Route
            index
            element={<Users />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="guilds"
          element={<GuildsLayout><Outlet /></GuildsLayout>}
        >
          <Route
            index
            element={<Guilds />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default AdministratorSubRouter
