// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import AuthenticationLayout from '~app/authentication.../layout'
import Authentication from '~app/authentication.../page'
import PasswordReset from '~app/authentication.../password-reset/page'

import NotFound from '~components/common/NotFound'

function AuthenticationSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<AuthenticationLayout><Outlet /></AuthenticationLayout>}
      >
        <Route
          index
          element={<Authentication />}
        />
        <Route
          path="password-reset"
          element={<Outlet />}
        >
          <Route
            index
            element={<PasswordReset />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default AuthenticationSubRouter
