// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import Legal from '~app/legal.../page'

import NotFound from '~components/common/NotFound'

function LegalSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<Outlet />}
      >
        <Route
          index
          element={<Legal />}
        />
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default LegalSubRouter
