// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import OnboardingLayout from '~app/onboarding.../layout'
import Onboarding from '~app/onboarding.../page'
import InstallExtension from '~app/onboarding.../install-extension/page'
import StartAdventure from '~app/onboarding.../start-adventure/page'

import NotFound from '~components/common/NotFound'

function OnboardingSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<OnboardingLayout><Outlet /></OnboardingLayout>}
      >
        <Route
          index
          element={<Onboarding />}
        />
        <Route
          path="install-extension"
          element={<Outlet />}
        >
          <Route
            index
            element={<InstallExtension />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="start-adventure"
          element={<Outlet />}
        >
          <Route
            index
            element={<StartAdventure />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default OnboardingSubRouter
