// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import StartAdventure from '~app/start-adventure.../page'

import NotFound from '~components/common/NotFound'

function StartAdventureSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<Outlet />}
      >
        <Route
          index
          element={<StartAdventure />}
        />
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default StartAdventureSubRouter
