// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import SupportLayout from '~app/support.../layout'
import Support from '~app/support.../page'

import NotFound from '~components/common/NotFound'

function SupportSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<SupportLayout><Outlet /></SupportLayout>}
      >
        <Route
          index
          element={<Support />}
        />
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default SupportSubRouter
