// ! Do not edit this file directly, use npm run router instead
import { Outlet, Route, Routes } from 'react-router-dom'

import TildeLayout from '~app/~.../layout'
import Tilde from '~app/~.../page'
import UserId from '~app/~.../[userId]/page'

import NotFound from '~components/common/NotFound'

function TildeSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<TildeLayout><Outlet /></TildeLayout>}
      >
        <Route
          index
          element={<Tilde />}
        />
        <Route
          path=":userId"
          element={<Outlet />}
        >
          <Route
            index
            element={<UserId />}
          />
          <Route
            path="*"
            element={<NotFound />}
          />
        </Route>
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default TildeSubRouter
